### ISSUE TITLE
[Segmentation fault (core dumped)] running `VintiCode`

### ISSUE THREAD

**Issue by capsulecorplab** [ODU-CGA-CubeSat/VintiCode#1]
Following [building VintiCode with cmake](https://github.com/ODU-CGA-CubeSat/VintiCode#build-with-cmake), running the `VintiCode` binary yields a `Segmentation fault (core dumped)` error.

Running gdb (GNU debugger) shows the following
```
[~/VintiCode/build]$ gdb VintiCode 
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from VintiCode...
(No debugging symbols found in VintiCode)
(gdb) run
Starting program: /home/kasm-user/VintiCode/build/VintiCode 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
__vfscanf_internal (s=0x0, 
    format=0x55555555c01d "%s %s %s %s %s %s", 
    argptr=argptr@entry=0x7fffffffe290, 
    mode_flags=mode_flags@entry=2) at vfscanf-internal.c:345
345	vfscanf-internal.c: No such file or directory.
(gdb) backtrace
#0  __vfscanf_internal (s=0x0, 
    format=0x55555555c01d "%s %s %s %s %s %s", 
    argptr=argptr@entry=0x7fffffffe290, 
    mode_flags=mode_flags@entry=2) at vfscanf-internal.c:345
#1  0x00007ffff7ac623d in __isoc99_fscanf (
    stream=<optimized out>, format=<optimized out>)
    at isoc99_fscanf.c:30
#2  0x0000555555555499 in main ()
```

**Comment by capsulecorplab** [comment]
resolved as per https://github.com/ODU-CGA-CubeSat/VintiCode/commit/43c7ddf25eb89c9cc998db973bdb0957e9023fe6
